### ISSUE TITLE
Installer warning about php8.3 when on php 8.3.10

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6640]
Local install, Windows, php 8.3.10:

![image](https://github.com/user-attachments/assets/12a0b5ea-14bd-45b8-8463-429a1491adfd)

**Comment by scottcwilson** [comment]
What version of Zen Cart are you using?

**Comment by torvista** [comment]
Github master

**Comment by scottcwilson** [comment]
Investigating.

**Comment by drbyte** [comment]
Unable to replicate. Granted, not running Windows.

**Comment by lat9** [comment]
I don't speak 'yaml', but my money's on the `.10` sub-version that's resulting in a miscompare.

**Comment by lat9** [comment]
I'll try to replicate ... later.

**Comment by drbyte** [comment]
systemChecks.yml
```yml
        method: checkPhpVersion
        parameters:
          version: 8.3.0
          versionTest: ge
```
The YAML reader reads the `8.3.0` as a string because it's got too many decimals to be a floating point number.

'ge' means "greater than or equal to"

`checkPhpVersion()`:
```php
return version_compare((string)PHP_VERSION, (string)$parameters['version'], (string)$parameters['versionTest']);
```

Using https://onlinephp.io to stage it, and selecting PHP version 8.3.10 from the versions list:
```php
<?php echo version_compare((string)PHP_VERSION, '8.3.0', 'ge');
```
returns 1 as expected

**Comment by torvista** [comment]
I repeated the install on another Windows pc which in theory has an identical local server setup but the error didn't show.
I don't have access to the original pc to test the indicated clause until tomorrow.

**Comment by drbyte** [comment]
@torvista if you can reproduce, try editing the yml file and wrapping the `8.3.0` inside quotes: `'8.3.0'`. It's never been needed before, but worth trying:

```yml
        method: checkPhpVersion
        parameters:
          version: '8.3.0'
          versionTest: ge
```
